[build-system]
requires = ["uv_build<0.13"]
build-backend = "uv_build"

[project]
name = "mri-utilities"
version = "0.1.0"
description = "Miscellaneous utilities to work with MRI data"
readme = "README.md"
requires-python = ">=3.14.7"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
    { name = "Raj Magesh Gauthaman", email = "mri-utilities@raj-magesh.org" },
]
keywords = ["MRI"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Typing :: Typed",
]
urls = { source = "https://codeberg.org/raj-magesh/mri-utilities" }
dependencies = [
    "requests>=2.34.2",
    "platformdirs>=4.11.7",
    "loguru>=0.7.3",
    "dcm2niix>=1.0.20260724",
    "heudiconv>=1.5.0",
    "nibabel>=5.4.2",
    "numpy>=2.5.2",
    "antspyx==0.5.3",         # FIXME(antspyx): bump version when antspy cuts a new release that allows a higher scipy (currently forces scipy<0.16)
    "tqdm>=4.70.0",
    "nilearn>=0.14.1",
]
import-names = ["mri_utilities"]

[dependency-groups]
dev = ["ruff", "ty", "deptry", "pytest", "sphinx"]

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[tool.deptry.per_rule_ignores]
DEP002 = ["heudiconv", "dcm2niix"]
